### ISSUE TITLE
Sincerely ask you a question

### ISSUE THREAD

**Issue by liweiyang2023** [gotutiyan/gector#4]
Hello, I am a developer exploring GEC. May I ask if this tool can summarize errors? I have now implemented a method to obtain errors and correct sentences, but I am unable to obtain the reason for the error

**Comment by gotutiyan** [comment]
Hello, the answer is No.
GECToR is a model for just correcting errors and cannot explain why.

While it may be possible to analyze the tokens associated with errors through analysis such as Attention, I do not believe there are any research.

I'm sure there are several studies that are similar to your interests (these are not related to GECToR):
- Enhancing Grammatical Error Correction Systems with Explanations
https://aclanthology.org/2023.acl-long.413/
- Controlled Generation with Prompt Insertion for Natural Language Explanations in Grammatical Error Correction
https://arxiv.org/abs/2309.11439

**Comment by liweiyang2023** [comment]
> Hello, the answer is No.您好，答案是否定的。 GECToR is a model for just correcting errors and cannot explain why.GECToR 是一个仅用于纠正错误的模型，无法解释原因。
> 
> While it may be possible to analyze the tokens associated with errors through analysis such as Attention, I do not believe there are any research.虽然可以通过诸如Attention之类的分析来分析与错误相关的标记，但我不认为有任何研究。
> 
> I'm sure there are several studies that are similar to your interests (these are not related to GECToR):我敢肯定有几项研究与您的兴趣相似（这些与GECToR无关）：
> 
> * Enhancing Grammatical Error Correction Systems with Explanations通过解释增强语法纠错系统
>   https://aclanthology.org/2023.acl-long.413/
> * Controlled Generation with Prompt Insertion for Natural Language Explanations in Grammatical Error Correction在语法纠错中对自然语言解释进行提示插入的受控生成
>   https://arxiv.org/abs/2309.11439

Thank you for your answer and providing information. I will take a closer look at this research
